import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "PRD-001",
    name: "Premium Cotton Polo",
    category: "Apparel",
    itemType: "Sellable Product",
    mrp: 1499,
    rate: 1199,
    taxType: "GST 12%",
    inclusion: "Incl.",
    hsn: "6105",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAN6vbqnwg9vInV_CZCwk7Kw-c9_sUrzxxaJiY7vk75nIIVOKjtp54YXDLgh8J3_Po4MgvhyJTuAqigHyxNmIQy_xzP6xHBJIYvd-eU2QLOpIkcBXQj7AwOvKaO2hFLCmi-MlQYc07oo-gcRSpwLHDWPn6KwobkmNg1CBpgANM3SQzYg9iN96FomV3EYjb8zTyhIgVVep8xeVUh93e7qRIspnAqzesnj9HPm8Qo7Qo5vqca6PAkN4L0v9T29XQ6gxBZ6nFGPSAdIWk6",
  },
  {
    id: "SRV-042",
    name: "Standard Tailoring",
    category: "Maintenance",
    itemType: "Sellable Product",
    mrp: 500,
    rate: 450,
    taxType: "GST 18%",
    inclusion: "Excl.",
    hsn: "9988",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDqChP2minNxRQzty84J0Zsyd3yysWvM4PS9EivumLOM5uLcO4hr0XgJdRbcFAoHabN4Tcycb_Gropa2XWYwVCSJgWDeAy7e-iMgEa0a88FeRVFfz7iEN9j8FzwAW1XBnW-qaBd_P38pYcg_OiUCw9NhvzMI3co8pNMuSqwDXY09WotF605bq5aAAMbms58Tu2ENE4_ZR6WjmoRASpEjdPgtCTdfIzCEq6LXtuzP-JBgKLK3CwszJnWkZKQs73x2l1RYV-PwbTADWri",
  },
  {
    id: "PRD-089",
    name: "Classic Oxfords",
    category: "Footwear",
    itemType: "Raw Material",
    mrp: 3999,
    rate: 3499,
    taxType: "GST 18%",
    inclusion: "Incl.",
    hsn: "6403",
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDqtVGKDIb3hHLrcKTI1_Ow63Ip17IqkPJIJJOF054pXKwVh4CkVhLPVuHdCs4TyBz1DqKS1K-eEnwNHEIklevJcCOI3cwWBk2SzraKz3_YbJXTAG8fAWPWqbj7t_wIXfXYnavwBWZVXEgl9RPZWNKDfizOvfwdj6ZIUyBvY3z5zvDuXGvr2jbEqyhRnhxxVHL7tIvz3LNaf2d-SXUzPS_MokUGiVUDJ4wPzcAk5Tk1bwxPZ67R6wMVkXb-QY5nmE1Iv2NCGcvp38bP",
  },
  {
    id: "PRD-004",
    name: "Linen Summer Shirt",
    category: "Apparel",
    itemType: "Sellable Product",
    mrp: 2299,
    rate: 1899,
    taxType: "GST 12%",
    inclusion: "Incl.",
    hsn: "6205",
  },
  {
    id: "PRD-005",
    name: "Slim Fit Chinos",
    category: "Apparel",
    itemType: "Sellable Product",
    mrp: 1899,
    rate: 1599,
    taxType: "GST 12%",
    inclusion: "Incl.",
    hsn: "6203",
  },
  {
    id: "RAW-001",
    name: "Silk Thread Spool",
    category: "Textiles",
    itemType: "Raw Material",
    mrp: 120,
    rate: 100,
    taxType: "GST 5%",
    inclusion: "Excl.",
    hsn: "5004",
  },
  {
    id: "PRD-007",
    name: "Designer Denim Jacket",
    category: "Apparel",
    itemType: "Sellable Product",
    mrp: 4499,
    rate: 3999,
    taxType: "GST 12%",
    inclusion: "Incl.",
    hsn: "6201",
  },
  {
    id: "PRD-008",
    name: "Woven Leather Belt",
    category: "Accessories",
    itemType: "Sellable Product",
    mrp: 999,
    rate: 799,
    taxType: "GST 18%",
    inclusion: "Incl.",
    hsn: "4203",
  },
  {
    id: "SRV-002",
    name: "Express Alteration",
    category: "Service",
    itemType: "Sellable Product",
    mrp: 300,
    rate: 250,
    taxType: "GST 18%",
    inclusion: "Excl.",
    hsn: "9988",
  },
  {
    id: "PRD-010",
    name: "Woolen Scarf",
    category: "Accessories",
    itemType: "Sellable Product",
    mrp: 750,
    rate: 599,
    taxType: "GST 5%",
    inclusion: "Incl.",
    hsn: "6214",
  },
  {
    id: "RAW-002",
    name: "Metal Buttons (Set)",
    category: "Hardware",
    itemType: "Raw Material",
    mrp: 45,
    rate: 35,
    taxType: "GST 18%",
    inclusion: "Excl.",
    hsn: "9606",
  },
  {
    id: "PRD-012",
    name: "Cargo Shorts",
    category: "Apparel",
    itemType: "Sellable Product",
    mrp: 1299,
    rate: 999,
    taxType: "GST 12%",
    inclusion: "Incl.",
    hsn: "6204",
  },
  {
    id: "PRD-013",
    name: "Graphic Tee",
    category: "Apparel",
    itemType: "Sellable Product",
    mrp: 699,
    rate: 499,
    taxType: "GST 5%",
    inclusion: "Incl.",
    hsn: "6109",
  },
  {
    id: "RAW-003",
    name: "Cotton Fabric Roll",
    category: "Textiles",
    itemType: "Raw Material",
    mrp: 5000,
    rate: 4200,
    taxType: "GST 5%",
    inclusion: "Excl.",
    hsn: "5208",
  },
  {
    id: "PRD-015",
    name: "Silk Necktie",
    category: "Accessories",
    itemType: "Sellable Product",
    mrp: 1150,
    rate: 899,
    taxType: "GST 12%",
    inclusion: "Incl.",
    hsn: "6215",
  },
  {
    id: "PRD-016",
    name: "Oxford Button-Down",
    category: "Apparel",
    itemType: "Sellable Product",
    mrp: 2499,
    rate: 2099,
    taxType: "GST 12%",
    inclusion: "Incl.",
    hsn: "6205",
  },
  {
    id: "PRD-017",
    name: "Canvas Tote Bag",
    category: "Accessories",
    itemType: "Sellable Product",
    mrp: 499,
    rate: 399,
    taxType: "GST 18%",
    inclusion: "Incl.",
    hsn: "4202",
  },
  {
    id: "RAW-004",
    name: "Zipper Pack (10pcs)",
    category: "Hardware",
    itemType: "Raw Material",
    mrp: 80,
    rate: 60,
    taxType: "GST 18%",
    inclusion: "Excl.",
    hsn: "9607",
  },
];
